Account screen
ErneDainesi/Parcial-TP3-Grupo-1 pull request #28
Opened 2024-10-13 19:58 UTC by NahuelLescano

2024-10-13 20:26 UTC, ErneDainesi requested changes
Chusmeate los comentarios que puse a ver si lo podemos meter aca

2024-10-13 20:26 UTC, ErneDainesi commented on app/src/main/java/com/example/parcial_tp3_grupo_1/AccountScreen.kt
> +        onClick = { /*TODO*/ },
Aca si es el boton de logout, no deberiamos hacer que te lleve al login?

2024-10-13 20:26 UTC, ErneDainesi commented on app/src/main/java/com/example/parcial_tp3_grupo_1/MainActivity.kt
> +            }
Habria que agregar la logica para evitar que te muestre la topbar en algunas pantallas y tambien para que te cambie el text dependiendo de cada ruta en la que estes

2024-10-13 20:27 UTC, ErneDainesi requested changes

2024-10-13 20:27 UTC, ErneDainesi commented on app/src/main/java/com/example/parcial_tp3_grupo_1/AccountScreen.kt
> +fun AccountScreen(modifier: Modifier = Modifier) {
Fijate la arquitectura que arme para las screens y adaptala a eso para este screen. Asi mantenemos coherencia con el codigo

2024-10-15 02:01 UTC, ErneDainesi requested changes, later dismissed

2024-10-15 02:01 UTC, ErneDainesi commented on app/src/main/java/com/example/parcial_tp3_grupo_1/screens/signin/SignInScreen.kt
> +        mutableStateOf(value = "don@gmail.com")
Entiendo que esto lo usaste para testing, fijate de borrarlo antes de mergear asi no queda en main

2024-10-15 15:24 UTC, ngvior approved these changes

2024-10-15 18:27 UTC, ErneDainesi approved these changes

2024-10-15 18:28 UTC, merged